// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

type Anime struct {
	ID           int32
	Titles       string
	Format       pgtype.Text
	Status       string
	Season       pgtype.Text
	SeasonYear   pgtype.Int4
	Episodes     pgtype.Int4
	CoverImage   pgtype.Text
	Genres       []string
	AverageScore pgtype.Int4
	Studio       []string
	LastUpdated  pgtype.Timestamptz
}

type AnimeDetail struct {
	ID                int32
	Description       pgtype.Text
	StartDate         sql.NullString
	EndDate           sql.NullString
	Duration          pgtype.Int4
	Source            pgtype.Text
	Trailer           pgtype.Text
	BannerImage       pgtype.Text
	Popularity        int32
	Trending          int32
	Favourites        int32
	AiringSchedule    sql.NullString
	Recommendations   []string
	ScoreDistribution sql.NullString
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Username     string
	AvatarUrl    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
