// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

const putMedia = `-- name: PutMedia :exec
INSERT INTO media (id,
                   titles,
                   type,
                   format,
                   status,
                   season,
                   season_year,
                   episodes,
                   chapters,
                   volumes,
                   cover_image,
                   genres,
                   average_score,
                   studios,
                   is_adult)
VALUES ($1,
        ROW($2, $3, $4)::titles,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17)
`

type PutMediaParams struct {
	ID           int32
	Column2      string
	Column3      string
	Column4      string
	Type         NullMediaType
	Format       pgtype.Text
	Status       string
	Season       pgtype.Text
	SeasonYear   pgtype.Int4
	Episodes     pgtype.Int4
	Chapters     pgtype.Int4
	Volumes      pgtype.Int4
	CoverImage   pgtype.Text
	Genres       []string
	AverageScore pgtype.Int4
	Studios      []string
	IsAdult      pgtype.Bool
}

func (q *Queries) PutMedia(ctx context.Context, arg PutMediaParams) error {
	_, err := q.db.Exec(ctx, putMedia,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Type,
		arg.Format,
		arg.Status,
		arg.Season,
		arg.SeasonYear,
		arg.Episodes,
		arg.Chapters,
		arg.Volumes,
		arg.CoverImage,
		arg.Genres,
		arg.AverageScore,
		arg.Studios,
		arg.IsAdult,
	)
	return err
}

const putMediaDetails = `-- name: PutMediaDetails :exec
INSERT INTO media_details (id,
                           description,
                           start_date,
                           end_date,
                           duration,
                           country,
                           source,
                           trailer,
                           banner_image,
                           popularity,
                           trending,
                           favourites,
                           airing_schedule,
                           recommendations,
                           score_distribution)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15
       )
`

type PutMediaDetailsParams struct {
	ID                int32
	Description       pgtype.Text
	StartDate         sql.NullString
	EndDate           sql.NullString
	Duration          pgtype.Int4
	Country           pgtype.Text
	Source            pgtype.Text
	Trailer           pgtype.Text
	BannerImage       pgtype.Text
	Popularity        int32
	Trending          int32
	Favourites        int32
	AiringSchedule    sql.NullString
	Recommendations   []string
	ScoreDistribution []string
}

func (q *Queries) PutMediaDetails(ctx context.Context, arg PutMediaDetailsParams) error {
	_, err := q.db.Exec(ctx, putMediaDetails,
		arg.ID,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Duration,
		arg.Country,
		arg.Source,
		arg.Trailer,
		arg.BannerImage,
		arg.Popularity,
		arg.Trending,
		arg.Favourites,
		arg.AiringSchedule,
		arg.Recommendations,
		arg.ScoreDistribution,
	)
	return err
}
