// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

const putMedia = `-- name: PutMedia :exec
INSERT INTO media (id,
                   titles,
                   type,
                   format,
                   status,
                   season,
                   season_year,
                   episodes,
                   chapters,
                   volumes,
                   cover_image,
                   genres,
                   average_score,
                   studios,
                   is_adult,
                   last_updated)
VALUES ($1,
        ROW($2, $3, $4)::titles,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        NOW()
        )
ON CONFLICT (id) DO UPDATE
SET titles        = ROW($2, $3, $4)::titles,
type          = $5,
format        = $6,
status        = $7,
season        = $8,
season_year   = $9,
episodes      = $10,
chapters      = $11,
volumes       = $12,
cover_image   = $13,
genres        = $14,
average_score = $15,
studios       = $16,
is_adult      = $17,
last_updated = NOW()
`

type PutMediaParams struct {
	ID           int32
	Column2      string
	Column3      string
	Column4      string
	Type         NullMediaType
	Format       pgtype.Text
	Status       string
	Season       pgtype.Text
	SeasonYear   pgtype.Int4
	Episodes     pgtype.Int4
	Chapters     pgtype.Int4
	Volumes      pgtype.Int4
	CoverImage   pgtype.Text
	Genres       []string
	AverageScore pgtype.Int4
	Studios      []string
	IsAdult      pgtype.Bool
}

func (q *Queries) PutMedia(ctx context.Context, arg PutMediaParams) error {
	_, err := q.db.Exec(ctx, putMedia,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Type,
		arg.Format,
		arg.Status,
		arg.Season,
		arg.SeasonYear,
		arg.Episodes,
		arg.Chapters,
		arg.Volumes,
		arg.CoverImage,
		arg.Genres,
		arg.AverageScore,
		arg.Studios,
		arg.IsAdult,
	)
	return err
}

const putMediaDetails = `-- name: PutMediaDetails :exec
INSERT INTO media_details (id,
                           description,
                           start_date,
                           end_date,
                           duration,
                           country,
                           source,
                           trailer,
                           banner_image,
                           popularity,
                           trending,
                           favourites,
                           airing_schedule,
                           recommendations,
                           score_distribution)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15)
ON CONFLICT (id) DO UPDATE
SET description        = $2,
start_date         = $3,
end_date           = $4,
duration           = $5,
country            = $6,
source             = $7,
trailer            = $8,
banner_image       = $9,
popularity         = $10,
trending           = $11,
favourites         = $12,
airing_schedule    = $13,
recommendations    = $14,
score_distribution = $15
`

type PutMediaDetailsParams struct {
	ID                int32
	Description       pgtype.Text
	StartDate         sql.NullString
	EndDate           sql.NullString
	Duration          pgtype.Int4
	Country           pgtype.Text
	Source            pgtype.Text
	Trailer           pgtype.Text
	BannerImage       pgtype.Text
	Popularity        int32
	Trending          int32
	Favourites        int32
	AiringSchedule    sql.NullString
	Recommendations   []string
	ScoreDistribution []string
}

func (q *Queries) PutMediaDetails(ctx context.Context, arg PutMediaDetailsParams) error {
	_, err := q.db.Exec(ctx, putMediaDetails,
		arg.ID,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Duration,
		arg.Country,
		arg.Source,
		arg.Trailer,
		arg.BannerImage,
		arg.Popularity,
		arg.Trending,
		arg.Favourites,
		arg.AiringSchedule,
		arg.Recommendations,
		arg.ScoreDistribution,
	)
	return err
}

const queryHighPrioMedia = `-- name: QueryHighPrioMedia :many
SELECT media.id
FROM media
LEFT JOIN media_details
ON media.id = media_details.id
WHERE (
    type = 'ANIME'
        AND (
        status IN ('RELEASING', 'NOT_YET_RELEASED')
            OR (
            status NOT IN ('RELEASING', 'NOT_YET_RELEASED')
                AND end_date IS NOT NULL
                AND EXTRACT(YEAR FROM CURRENT_DATE) = (end_date).year
		    AND EXTRACT(MONTH FROM CURRENT_DATE) - (end_date).month <= 1
            )
        )
    )
OR (
type = 'MANGA'
    AND popularity >= 500
    AND (
    status IN ('RELEASING', 'NOT_YET_RELEASED')
        OR (
        status NOT IN ('RELEASING', 'NOT_YET_RELEASED')
            AND end_date IS NOT NULL
            AND EXTRACT(YEAR FROM CURRENT_DATE) = (end_date).year
        AND EXTRACT(MONTH FROM CURRENT_DATE) - (end_date).month <= 1
        )
    )
)
`

func (q *Queries) QueryHighPrioMedia(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, queryHighPrioMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
